framework:
    esi: false
    secret: "%secret%"
    form: ~
    csrf_protection: ~
#    error_controller: Surfnet\StepupBundle\Controller\ExceptionController::show
    validation: { enable_annotations: true }
    trusted_hosts: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
        name: sess_selfservice
        cookie_httponly: true
        cookie_secure: true
    fragments: false
    http_method_override: true

when@dev:
    framework:
        router:
            strict_requirements: true
        profiler: { only_exceptions: false }

when@test:
    framework:
        test: ~
        session:
            #storage_id: session.storage.mock_file
            storage_factory_id: session.storage.factory.mock_file
        profiler:
            collect: false
