framework:
  #esi:             ~
  secret:          "%secret%"
  form:            ~
  csrf_protection: ~
  validation:      { enable_annotations: true }
  templating:
    engines: ['twig']
  trusted_hosts:   ~
  session:
    # handler_id set to null will use default session handler from php.ini
    handler_id:  ~
    name: sess_selfservice
    cookie_httponly: true
    cookie_secure: true
  fragments:       ~
  http_method_override: true
