# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    esi: false
    secret: "%secret%"
    form: ~
    csrf_protection: ~
    trusted_hosts: ~
    annotations: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
        name: sess_selfservice
        cookie_httponly: true
        cookie_secure: true
        cookie_samesite: none
        cookie_lifetime: 0
        gc_maxlifetime: 0


    fragments: false
    error_controller: Surfnet\StepupSelfService\SelfServiceBundle\Controller\ExceptionController::show
    http_method_override: true
    php_errors:
        log: true

    default_locale: '%default_locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%default_locale%'
    router:
        utf8: true

when@dev:
    framework:
        router:
            strict_requirements: true
        profiler: { only_exceptions: false }

when@test:
    framework:
        test: ~
        session:
            storage_factory_id: session.storage.factory.mock_file
        profiler:
            collect: false

when@prod:
    framework:
        router:
            strict_requirements: null
