monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
  handlers:
    prod-signaler:
      type: fingers_crossed
      action_level: ERROR
      passthru_level: NOTICE # this means that all message of level NOTICE or higher are always logged
      handler: main_stdout
      channels: [ "!event" ]
      bubble: false # if we handle it, nothing else should
    main_stdout:
      type: stream
      ident: stepup-selfservice
      path: "php://stderr"
      formatter: surfnet_stepup.monolog.json_formatter

when@dev:
  monolog:
    handlers:
      prod-signaler:
        action_level: ERROR
        passthru_level: DEBUG # DEV setting: this means that all message of level DEBUG or higher are always logged
        channels: [ "!event" ]
        bubble: true
      main_logfile:
        type: stream
        handler: logfile
        level: NOTICE
        path: "%kernel.logs_dir%/%kernel.environment%.log"
      deprecation:
        type: rotating_file
        path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        max_files: 2
        channels: [ deprecation ]

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [ 404, 405 ]
        channels: [ "!event" ]
      deprecation:
        type: rotating_file
        path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        max_files: 2
        channels: [ deprecation ]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
