nelmio_security:
  clickjacking:
    paths:
      '^/.*': DENY
  # Content Security Policy
  csp:
    # Log to security channel
    report_logger_service: monolog.logger.security
    enforce:
      report-uri: "%router.request_context.base_url%/csp/report"
      default-src:
        - 'self'
      block-all-mixed-content: true # defaults to false, blocks HTTP content over HTTPS transport
      upgrade-insecure-requests: true # defaults to false, upgrades HTTP requests to HTTPS transport

  content_type:
    nosniff: true
  xss_protection:
    enabled: true
    mode_block: true
  forced_ssl:
    enabled: true
    hsts_max_age: 31536000 # 365 days
    hsts_subdomains: true

when@dev: &nelmio_dev
  nelmio_security:
    csp:
      enforce:
        img-src: [ self, 'data:' ]
        script-src: [ self, unsafe-inline ]
        style-src: [ self, unsafe-inline ]

when@test: *nelmio_dev # use same config as dev
