security:
    providers:
        middleware:
            id: self_service.service.identity

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/|^/_trans(/|$)
            security: false

        default:
            pattern: ^/authentication/(metadata|session-expired)$

        monitor:
            pattern: ^/(info|health)$
            security: false

        csp_report:
            pattern: ^/csp/report$
            security: false

        saml_based:
            custom_authenticators:
                - Surfnet\SamlBundle\Security\Authentication\SamlAuthenticator

    access_control:
        - { path: ^/saml, roles: PUBLIC_ACCESS, requires_channel: https }
        - { path: ^/authentication, roles: PUBLIC_ACCESS, requires_channel: https }
        - { path: ^/, roles: ROLE_USER, requires_channel: https }
