surfnet_stepup_self_service_self_service:
  enabled_second_factors: "%enabled_second_factors%"
  enabled_generic_second_factors: "%enabled_generic_second_factors%"
  second_factor_test_identity_provider:
    entity_id: "%second_factor_test_idp_entity_id%"
    sso_url: "%second_factor_test_idp_sso_url%"
    certificate: "%second_factor_test_idp_certificate%"
  session_lifetimes:
    max_absolute_lifetime: "%session_max_absolute_lifetime%"
    max_relative_lifetime: "%session_max_relative_lifetime%"
  preferred_activation_flow:
    query_string_field_name: "%preferred_activation_flow_name%"
    options: "%preferred_activation_flow_options%"
