twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_4_layout.html.twig','@SurfnetStepupSelfServiceSelfService/form/fields.html.twig' ]
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        global_view_parameters: "@self_service.service.global_view_parameters"
        root_path: "%kernel.project_dir%"
    paths:
        '%kernel.project_dir%/src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views': 'SurfnetStepupSelfServiceSelfServiceBundle'
        '%kernel.project_dir%/vendor/surfnet/stepup-saml-bundle/templates': 'SurfnetSaml'

when@test:
    twig:
        strict_variables: true
