services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true


    # Todo Paul: why is this not aoutwired in the extention?
    Surfnet\StepupSelfService\SamlStepupProviderBundle\Provider\MetadataFactoryCollection:

    gssp.provider_repository:
        class: Surfnet\StepupSelfService\SamlStepupProviderBundle\Provider\ProviderRepository
    Surfnet\StepupSelfService\SamlStepupProviderBundle\Provider\ProviderRepository:
        alias: gssp.provider_repository

