services:
    # To be compatible with loading services from the container instead of using DI, TODO, Utilize DI throughout the
    # application.
    _defaults: { public: true }

    gssp.provider_repository:
        class: Surfnet\StepupSelfService\SamlStepupProviderBundle\Provider\ProviderRepository

    gssp.sessionbag:
        class: Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag
#        factory: ['@session', 'getBag']
        arguments: ['gssp']

    gssp.session.attribute_bag:
        public: false
        class: Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag
        arguments:
            - '__gssp__'
        calls:
            - [setName, ['gssp']]
