controllers:
#    resource: ../../src/Controller/
    resource: ../../src/Surfnet/StepupSelfService/SelfServiceBundle/Controller
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
