imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%default_locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: sess_selfservice
        cookie_httponly: true
        cookie_secure: true
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [MopaBootstrapBundle, SurfnetStepupSelfServiceSelfServiceBundle]
    #java: /usr/bin/java
    node: "/usr/bin/node"
    node_paths: ["/usr/lib/node_modules"]
    filters:
        cssrewrite: ~
        less: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

nelmio_security:
    # Content Security Policy
    csp:
        report_uri: /csp/report
        # Log to security channel
        report_logger_service: monolog.logger.security
        # Content types: default, script, object, style, img, media, frame, font, connect
        default: [ self ]
    signed_cookie:
        names: ['*']
    encrypted_cookie:
        names: ['*']

services:
    twig.extension.text: # Required by JMSTranslationBundle
        class: Twig_Extensions_Extension_Text
        tags: [{ name: twig.extension }]

surfnet_stepup_middleware_client:
    authorisation:
        username: ss
        password: bar
    url:
        command_api: 'http://mw-dev.stepup.coin.surf.net/app_dev.php/command'
        api: 'http://mw-dev.stepup.coin.surf.net/app_dev.php/'

surfnet_saml:
    hosted:
        service_provider:
            enabled: true
            assertion_consumer_route: selfservice_serviceprovider_consume_assertion
            public_key: %saml_sp_publickey%
            private_key: %saml_sp_privatekey%
        metadata:
            entity_id_route: selfservice_saml_metadata
            public_key: %saml_metadata_publickey%
            private_key: %saml_metadata_privatekey%
    remote:
        identity_provider:
            enabled: true
            entity_id: %saml_remote_idp_entity_id%
            sso_url: %saml_remote_idp_sso_url%
            certificate: %saml_remote_idp_certificate%

surfnet_stepup:
    logging:
        application_name: self-service
