imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: samlstepupproviders.yml }
    - { resource: global_view_parameters.yml }
    - { resource: logging.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%default_locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    assets:
        version: "%asset_version%"
    default_locale:  "%default_locale%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: sess_selfservice
        cookie_httponly: true
        cookie_secure: true
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: SurfnetStepupSelfServiceSelfServiceBundle:Exception:show
    globals:
        global_view_parameters: "@self_service.service.global_view_parameters"
        root_path: "%kernel.root_dir%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [MopaBootstrapBundle, SurfnetStepupSelfServiceSelfServiceBundle]
    #java: /usr/bin/java
    node: "/usr/bin/node"
    node_paths: ["/usr/lib/node_modules"]
    filters:
        cssrewrite: ~
        less: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

nelmio_security:
    clickjacking:
        paths:
            '^/.*': DENY
    # Content Security Policy
    csp:
        report_uri: /csp/report
        # Log to security channel
        report_logger_service: monolog.logger.security
        # Content types: default, script, object, style, img, media, frame, font, connect
        default: [ self ]

mopa_bootstrap:
    form:
        show_legend: false
        templating: SurfnetStepupSelfServiceSelfServiceBundle:Form:fields.html.twig
    icons:
        icon_set: fontawesome4

services:
    twig.extension.text: # Required by JMSTranslationBundle
        class: Twig_Extensions_Extension_Text
        tags: [{ name: twig.extension }]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags: [{ name: twig.extension }]

surfnet_stepup_middleware_client:
    authorisation:
        username: "%middleware_credentials_username%"
        password: "%middleware_credentials_password%"
    url:
        command_api: "%middleware_url_command_api%"
        api: "%middleware_url_api%"

surfnet_saml:
    hosted:
        attribute_dictionary:
            ignore_unknown_attributes: true
        service_provider:
            enabled: true
            assertion_consumer_route: selfservice_serviceprovider_consume_assertion
            public_key: "%saml_sp_publickey%"
            private_key: "%saml_sp_privatekey%"
        metadata:
            entity_id_route: selfservice_saml_metadata
            public_key: "%saml_metadata_publickey%"
            private_key: "%saml_metadata_privatekey%"
    remote:
        identity_provider:
            enabled: true
            entity_id: "%saml_remote_idp_entity_id%"
            sso_url: "%saml_remote_idp_sso_url%"
            certificate: "%saml_remote_idp_certificate%"

surfnet_stepup:
    logging:
        application_name: self-service
    loa_definition:
        loa1: "%stepup_loa_loa1%"
        loa2: "%stepup_loa_loa2%"
        loa3: "%stepup_loa_loa3%"
    sms:
        originator: "%sms_originator%"
        otp_expiry_interval: "%sms_otp_expiry_interval%"
        maximum_otp_requests: "%sms_maximum_otp_requests%"
    gateway_api:
        url: "%gateway_api_url%"
        credentials:
            username: "%gateway_api_username%"
            password: "%gateway_api_password%"
    attach_request_id_injector_to:
        - surfnet_stepup.guzzle.gateway_api
        - surfnet_stepup_middleware_client.guzzle.api
        - surfnet_stepup_middleware_client.guzzle.commands
    locale_cookie:
        domain: "%locale_cookie_domain%"

jms_translation:
    locales: "%locales%"
    configs:
        default:
            dirs: ["%kernel.root_dir%/../src", "%kernel.root_dir%", "%kernel.root_dir%/../vendor/surfnet"]
            output_dir: "%kernel.root_dir%/Resources/translations"
            ignored_domains: []
            excluded_names: ['*TestCase.php', '*Test.php']
            excluded_dirs: [cache, data, logs, Tests]
            extractors: []

surfnet_stepup_self_service_self_service:
    enabled_second_factors: "%enabled_second_factors%"
    enabled_generic_second_factors: "%enabled_generic_second_factors%"
    second_factor_test_identity_provider:
        entity_id: "%second_factor_test_idp_entity_id%"
        sso_url: "%second_factor_test_idp_sso_url%"
        certificate: "%second_factor_test_idp_certificate%"
    session_lifetimes:
        max_absolute_lifetime: "%session_max_absolute_lifetime%"
        max_relative_lifetime: "%session_max_relative_lifetime%"
