parameters:
  saml_rv_publickey: "%kernel.project_dir%/src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Resources/test.crt"
  saml_rv_privatekey: "%kernel.project_dir%/src/Surfnet/StepupSelfService/SelfServiceBundle/Tests/Resources/test.key"

  remote_vetting_idps:
      - name: mock_idp
        entityId: https://selfservice.stepup.example.com/mock/metadata
        ssoUrl: https://selfservice.stepup.example.com/second-factor/mock/sso
        certificateFile: "%saml_rv_publickey%"
        privateKey: "%saml_rv_privatekey%"
  remote_vetting_sp:
    entityId: https://selfservice.stepup.example.com/saml/metadata
    assertionConsumerUrl: https://selfservice.stepup.example.com/second-factor/acs
    privateKey: "%saml_rv_privatekey%"

  identity_encryption_configuration:
    encryption_public_key: |
        -----BEGIN CERTIFICATE-----
        MIIC6jCCAdICCQC9cRx5wiwWOjANBgkqhkiG9w0BAQsFADA3MRwwGgYDVQQDDBNT
        ZWxmU2VydmljZSBTQU1MIFNQMRcwFQYDVQQKDA5EZXZlbG9wbWVudCBWTTAeFw0x
        ODA3MzAxMjMwNDdaFw0yMzA3MjkxMjMwNDdaMDcxHDAaBgNVBAMME1NlbGZTZXJ2
        aWNlIFNBTUwgU1AxFzAVBgNVBAoMDkRldmVsb3BtZW50IFZNMIIBIjANBgkqhkiG
        9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqhbI0Xy682DuvWchg6FYnI+DNwLXef2XExM4
        YVRBaMMsOZ3rBtQUTMSqYan6SK/BOEXLs0rNiJjyM0dn+F98wg3fv5zIADlvfk3L
        BVdcGsrpVfFUWtSa73yMgbROy8/RJADbUJE/HUB3ZmdjdiuD2Cui2aoWwT2HR8uk
        Jwmoxiu45IWFPbqPQ7/1mH644JPOWTPLTv4OGGLQo8MNrP1oRCiZ0IEL4CQeGOOj
        u5rfIJ0bTVm0UmelT4hGaqZovBMwXp3QV41akJ7UEMEBK2YMnLQy47Xuzi7aTDhJ
        lvHcJ8mfH2NbjRh7hJoACVRTvQloxajgkr1iGMiWiiqT0e+YYwIDAQABMA0GCSqG
        SIb3DQEBCwUAA4IBAQBwZ0gRHvR8B8KivrXrhWNL9uLvWhEAH7OiDqo+fywkBp5K
        EuDJcbbvEPftHunSAGylg7M2xKuBIGamFpp74WDJccrtZ1jJ4qqnacUDRQrTLqqM
        ZKqGpFOU0xjKkSxSGRuMtGN9/7er/TeonjQ0XBvjYvTomy3b5aCLVWRvEfKu2g1s
        Dd8uhr62RY/HfMgidEt7LHDolkCVg+6JzY3OTcgeHga3cvYObOYPplxw1YPq5+Bq
        qxaUW4nfb5DtK33bZBYMeyV6BZtSggc5Z/19aPx/s0bf6ySTUyB3lRqe5d3etCns
        4bGidORCl/6EZiXwVcPvmYmxYXqmuNWfps7isUvo
        -----END CERTIFICATE-----
    storage_location: "%kernel.project_dir%/app/rv"

services:
  self_service.remote_vetting.identity_provider_factory:
    class: Surfnet\StepupSelfService\SelfServiceBundle\Service\RemoteVetting\IdentityProviderFactory
    arguments:
      - "%remote_vetting_idps%"

  self_service.remote_vetting.service_provider_factory:
    class: Surfnet\StepupSelfService\SelfServiceBundle\Service\RemoteVetting\ServiceProviderFactory
    arguments:
      - "%remote_vetting_sp%"

  Surfnet\StepupSelfService\SelfServiceBundle\RemoteVetting\Configuration\RemoteVettingConfiguration:
    arguments:
      $configurationSettings: "%identity_encryption_configuration%"
      $version: "%asset_version%"

  self_service.remote_vetting.remote_vetting_context:
    class: Surfnet\StepupSelfService\SelfServiceBundle\Service\RemoteVetting\RemoteVettingContext
    arguments:
      $session: "@session"

  self_service.remote_vetting.saml_callout_helper:
    class: Surfnet\StepupSelfService\SelfServiceBundle\Service\RemoteVetting\SamlCalloutHelper
    arguments:
      $identityProviderFactory: "@self_service.remote_vetting.identity_provider_factory"
      $serviceProviderFactory: "@self_service.remote_vetting.service_provider_factory"
      $postBinding: "@surfnet_saml.http.post_binding"
      $remoteVettingService: "@self_service.remote_vetting.service"
      $logger: "@logger"

  self_service.remote_vetting.service:
    class: Surfnet\StepupSelfService\SelfServiceBundle\Service\RemoteVettingService
    arguments:
      $remoteVettingContext: "@self_service.remote_vetting.remote_vetting_context"
      $identityEncrypter: "@self_service.remote_vetting.service.identity_encrypter"
      $logger: "@logger"

  Surfnet\StepupSelfService\SelfServiceBundle\Controller\RemoteVettingController:
    arguments:
      - "@self_service.remote_vetting.service"
      - "@self_service.remote_vetting.saml_callout_helper"
      - "@logger"

  Surfnet\StepupSelfService\SelfServiceBundle\Mock\RemoteVetting\MockConfiguration:
    arguments:
      $identityProviderEntityId: 'https://selfservice.stepup.example.com/mock/idp/metadata'
      $serviceProviderEntityId: 'https://selfservice.stepup.example.com/saml/metadata'
      $privateKeyPath: '%saml_rv_privatekey%'
      $publicCertPath: '%saml_rv_publickey%'

  Surfnet\StepupSelfService\SelfServiceBundle\Mock\RemoteVetting\MockRemoteVetController:
    arguments:
      - '@Surfnet\StepupSelfService\SelfServiceBundle\Mock\RemoteVetting\MockGateway'
      - '@twig'

  Surfnet\StepupSelfService\SelfServiceBundle\Mock\RemoteVetting\MockGateway:
      class: Surfnet\StepupSelfService\SelfServiceBundle\Mock\RemoteVetting\MockGateway
      arguments:
        - '@Surfnet\StepupSelfService\SelfServiceBundle\Mock\RemoteVetting\MockConfiguration'

  Surfnet\StepupSelfService\SelfServiceBundle\RemoteVetting\Service\IdentityFilesystemWriter:
    arguments:
      - '@Surfnet\StepupSelfService\SelfServiceBundle\RemoteVetting\Configuration\RemoteVettingConfiguration'


  self_service.remote_vetting.service.identity_encrypter:
    class: Surfnet\StepupSelfService\SelfServiceBundle\RemoteVetting\Service\IdentityEncrypter
    arguments:
      $configuration: '@Surfnet\StepupSelfService\SelfServiceBundle\RemoteVetting\Configuration\RemoteVettingConfiguration'
      $writer: '@Surfnet\StepupSelfService\SelfServiceBundle\RemoteVetting\Service\IdentityFilesystemWriter'