parameters:

  remote_vetting_idps:
      - name: mock_idp
        entityId: https://selfservice.stepup.example.com/mock/metadata
        ssoUrl: https://selfservice.stepup.example.com/second-factor/mock/sso
        certificateFile: "%saml_sp_publickey%"
        privateKey: "%saml_sp_publickey%"
  remote_vetting_sp:
    entityId: https://selfservice.stepup.example.com/saml/metadata
    assertionConsumerUrl: https://selfservice.stepup.example.com/second-factor/acs
    privateKey: "%saml_sp_privatekey%"

  identity_encryption_configuration:
    encryption_public_key: |-
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyOZnmunnDgF4ivLai3zA
      7BeI7RDgP1cWp6TLgaLKHnomzE/ytn93SOl7fnw+vPLdQ3jNIbOiULos9Lt0vyJq
      hduC5ykPwC/C+oJqM4YBDUvOdtyKrvKs4/IplUibeB0NC1f/JvayfkT9da+Dx165
      6PndKDeUHUpho1EsK5ylKYFQCsQjktIhb1Z6WEUdDMZee+syPzefSSVaJMiZIRbF
      fvbcqoQMtmR+1Ua/HuXdBFk53+7GqWzF/0Rx/Lcf8u97TIAiYTA/4g1sM3KW8YOM
      CRXjEAAMc04Ok2KnFgFsjefEOLDWlPOueTp31+HShsjEkhwZ2RMXMV18bPV3wD7X
      lwIDAQAB
      -----END PUBLIC KEY-----
    storage_location: /tmp/

services:

  self_service.remote_vetting.identity_provider_factory:
    class: Surfnet\StepupSelfService\SelfServiceBundle\Service\RemoteVetting\IdentityProviderFactory
    arguments:
      - "%remote_vetting_idps%"

  self_service.remote_vetting.service_provider_factory:
    class: Surfnet\StepupSelfService\SelfServiceBundle\Service\RemoteVetting\ServiceProviderFactory
    arguments:
      - "%remote_vetting_sp%"

  Surfnet\StepupSelfService\SelfServiceBundle\RemoteVetting\Configuration\RemoteVettingConfiguration:
    arguments:
      $configurationSettings: "%identity_encryption_configuration%"
      $version: "%asset_version%"


  self_service.remote_vetting.service:
    class: Surfnet\StepupSelfService\SelfServiceBundle\Service\RemoteVettingService
    arguments:
      $identityProviderFactory: "@self_service.remote_vetting.identity_provider_factory"
      $serviceProviderFactory: "@self_service.remote_vetting.service_provider_factory"
      $postBinding: "@surfnet_saml.http.post_binding"
      $session: "@session"
      $logger: "@logger"

  Surfnet\StepupSelfService\SelfServiceBundle\Controller\RemoteVettingController:
    arguments:
      - "@self_service.remote_vetting.service"

  Surfnet\StepupSelfService\SelfServiceBundle\Mock\RemoteVetting\MockGateway:
    arguments:
      - '@Surfnet\StepupSelfService\SelfServiceBundle\Mock\RemoteVetting\MockConfiguration'

  Surfnet\StepupSelfService\SelfServiceBundle\Mock\RemoteVetting\MockConfiguration:
    arguments:
      $identityProviderEntityId: 'https://selfservice.stepup.example.com/mock/idp/metadata'
      $serviceProviderEntityId: 'https://selfservice.stepup.example.com/saml/metadata'
      $privateKeyPath: '%saml_sp_privatekey%'
      $publicCertPath: '%saml_sp_publickey%'

  Surfnet\StepupSelfService\SelfServiceBundle\Mock\RemoteVetting\MockRemoteVetController:
    arguments:
      - '@Surfnet\StepupSelfService\SelfServiceBundle\Mock\RemoteVetting\MockGateway'
      - '@twig'
