imports:
    - { resource: samlstepupproviders_parameters.yml }

surfnet_stepup_self_service_saml_stepup_provider:
    routes:
        consume_assertion: ss_registration_gssf_consume_assertion
        metadata: ss_registration_gssf_saml_metadata
    providers:
        tiqr:
            hosted:
                service_provider:
                    public_key: "%gssp_tiqr_sp_publickey%"
                    private_key: "%gssp_tiqr_sp_privatekey%"
                metadata:
                    public_key: "%gssp_tiqr_metadata_publickey%"
                    private_key: "%gssp_tiqr_metadata_privatekey%"
            remote:
                entity_id: "%gssp_tiqr_remote_entity_id%"
                sso_url: "%gssp_tiqr_remote_sso_url%"
                certificate: "%gssp_tiqr_remote_certificate%"
            view_config:
                loa: "%gssp_tiqr_loa%"
                logo: "%gssp_tiqr_logo%"
                alt: "%gssp_tiqr_alt%"
                title: "%gssp_tiqr_title%"
                description: "%gssp_tiqr_description%"
                button_use: "%gssp_tiqr_button_use%"
                initiate_title: "%gssp_tiqr_initiate_title%"
                initiate_button: "%gssp_tiqr_initiate_button%"
                explanation: "%gssp_tiqr_explanation%"
                authn_failed: "%gssp_tiqr_authn_failed%"
                pop_failed: "%gssp_tiqr_pop_failed%"
                app_android_url: "%gssp_tiqr_app_android_url%"
                app_ios_url: "%gssp_tiqr_app_ios_url%"
        biometric:
            hosted:
                service_provider:
                    public_key: "%gssp_biometric_sp_publickey%"
                    private_key: "%gssp_biometric_sp_privatekey%"
                metadata:
                    public_key: "%gssp_biometric_metadata_publickey%"
                    private_key: "%gssp_biometric_metadata_privatekey%"
            remote:
                entity_id: "%gssp_biometric_remote_entity_id%"
                sso_url: "%gssp_biometric_remote_sso_url%"
                certificate: "%gssp_biometric_remote_certificate%"
            view_config:
                loa: "%gssp_biometric_loa%"
                logo: "%gssp_biometric_logo%"
                alt: "%gssp_biometric_alt%"
                title: "%gssp_biometric_title%"
                description: "%gssp_biometric_description%"
                button_use: "%gssp_biometric_button_use%"
                initiate_title: "%gssp_biometric_initiate_title%"
                initiate_button: "%gssp_biometric_initiate_button%"
                explanation: "%gssp_biometric_explanation%"
                authn_failed: "%gssp_biometric_authn_failed%"
                pop_failed: "%gssp_biometric_pop_failed%"
