imports:
    - { resource: samlstepupproviders_parameters.yaml }

surfnet_stepup_self_service_saml_stepup_provider:
    routes:
        consume_assertion: ss_registration_gssf_consume_assertion
        metadata: ss_registration_gssf_saml_metadata

    providers:
        webauthn:
            hosted:
                service_provider:
                    public_key: "%gssp_webauthn_sp_publickey%"
                    private_key: "%gssp_webauthn_sp_privatekey%"
                metadata:
                    public_key: "%gssp_webauthn_metadata_publickey%"
                    private_key: "%gssp_webauthn_metadata_privatekey%"
            remote:
                entity_id: "%gssp_webauthn_remote_entity_id%"
                sso_url: "%gssp_webauthn_remote_sso_url%"
                certificate: "%gssp_webauthn_remote_certificate%"
            view_config:
                loa: 3
                logo: "%gssp_webauthn_logo%"
                alt: "%gssp_webauthn_alt%"
                title: "%gssp_webauthn_title%"
                description: "%gssp_webauthn_description%"
                button_use: "%gssp_webauthn_button_use%"
                initiate_title: "%gssp_webauthn_initiate_title%"
                initiate_button: "%gssp_webauthn_initiate_button%"
                explanation: "%gssp_webauthn_explanation%"
                authn_failed: "%gssp_webauthn_authn_failed%"
                pop_failed: "%gssp_webauthn_pop_failed%"
                app_android_url: "%gssp_webauthn_app_android_url%"
                app_ios_url: "%gssp_webauthn_app_ios_url%"
        demo_gssp_2:
            hosted:
                service_provider:
                    public_key: "%gssp_demo_gssp_2_sp_publickey%"
                    private_key: "%gssp_demo_gssp_2_sp_privatekey%"
                metadata:
                    public_key: "%gssp_demo_gssp_2_metadata_publickey%"
                    private_key: "%gssp_demo_gssp_2_metadata_privatekey%"
            remote:
                entity_id: "%gssp_demo_gssp_2_remote_entity_id%"
                sso_url: "%gssp_demo_gssp_2_remote_sso_url%"
                certificate: "%gssp_demo_gssp_2_remote_certificate%"
            view_config:
                loa: 3
                logo: "%gssp_demo_gssp_2_logo%"
                alt: "%gssp_demo_gssp_2_alt%"
                title: "%gssp_demo_gssp_2_title%"
                description: "%gssp_demo_gssp_2_description%"
                button_use: "%gssp_demo_gssp_2_button_use%"
                initiate_title: "%gssp_demo_gssp_2_initiate_title%"
                initiate_button: "%gssp_demo_gssp_2_initiate_button%"
                explanation: "%gssp_demo_gssp_2_explanation%"
                authn_failed: "%gssp_demo_gssp_2_authn_failed%"
                pop_failed: "%gssp_demo_gssp_2_pop_failed%"
                app_android_url: "%gssp_demo_gssp_2_app_android_url%"
                app_ios_url: "%gssp_demo_gssp_2_app_ios_url%"
        tiqr:
            hosted:
                service_provider:
                    public_key: "%gssp_tiqr_sp_publickey%"
                    private_key: "%gssp_tiqr_sp_privatekey%"
                metadata:
                    public_key: "%gssp_tiqr_metadata_publickey%"
                    private_key: "%gssp_tiqr_metadata_privatekey%"
            remote:
                entity_id: "%gssp_tiqr_remote_entity_id%"
                sso_url: "%gssp_tiqr_remote_sso_url%"
                certificate: "%gssp_tiqr_remote_certificate%"
            view_config:
                loa: 2
                logo: "%gssp_tiqr_logo%"
                alt: "%gssp_tiqr_alt%"
                title: "%gssp_tiqr_title%"
                description: "%gssp_tiqr_description%"
                button_use: "%gssp_tiqr_button_use%"
                initiate_title: "%gssp_tiqr_initiate_title%"
                initiate_button: "%gssp_tiqr_initiate_button%"
                explanation: "%gssp_tiqr_explanation%"
                authn_failed: "%gssp_tiqr_authn_failed%"
                pop_failed: "%gssp_tiqr_pop_failed%"
                app_android_url: "%gssp_tiqr_app_android_url%"
                app_ios_url: "%gssp_tiqr_app_ios_url%"
        demo_gssp:
            hosted:
                service_provider:
                    public_key: "%gssp_demo_gssp_sp_publickey%"
                    private_key: "%gssp_demo_gssp_sp_privatekey%"
                metadata:
                    public_key: "%gssp_demo_gssp_metadata_publickey%"
                    private_key: "%gssp_demo_gssp_metadata_privatekey%"
            remote:
                entity_id: "%gssp_demo_gssp_remote_entity_id%"
                sso_url: "%gssp_demo_gssp_remote_sso_url%"
                certificate: "%gssp_demo_gssp_remote_certificate%"
            view_config:
                loa: 2
                logo: "%gssp_demo_gssp_logo%"
                alt: "%gssp_demo_gssp_alt%"
                title: "%gssp_demo_gssp_title%"
                description: "%gssp_demo_gssp_description%"
                button_use: "%gssp_demo_gssp_button_use%"
                initiate_title: "%gssp_demo_gssp_initiate_title%"
                initiate_button: "%gssp_demo_gssp_initiate_button%"
                explanation: "%gssp_demo_gssp_explanation%"
                authn_failed: "%gssp_demo_gssp_authn_failed%"
                pop_failed: "%gssp_demo_gssp_pop_failed%"
                app_android_url: "%gssp_demo_gssp_app_android_url%"
                app_ios_url: "%gssp_demo_gssp_app_ios_url%"
