FROM ghcr.io/openconext/openconext-basecontainers/php85-apache2-node24:latest

RUN rm -rf /etc/apache2/sites-enabled/*
COPY ./docker/conf/apache2.conf /etc/apache2/sites-enabled/apache2.conf
EXPOSE 80

# Set the default workdir
WORKDIR /var/www/html

CMD ["apache2-foreground"]
