imports:
  - { resource: 'legacy/samlstepupproviders_parameters.yaml' }
  - { resource: 'legacy/global_view_parameters.yaml' }
  - { resource: 'legacy/parameters.yaml' }
  - { resource: 'legacy/samlstepupproviders.yaml' }

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true

  Surfnet\StepupSelfService\SelfServiceBundle\Controller\:
    # Setting class is redundant, but adds autocompletions for the IDE.
    resource: '../src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/'
    public: true
#    class: Surfnet\StepupSelfService\SelfServiceBundle\Controller\Controller
#    arguments:
    # Add this tag to inject services into controller actions.
    tags: ['controller.service_arguments']
    # Call the setContainer method to get access to the services via
    # $this->get() method.
    calls:
      - setContainer: ['@service_container']

  logger:
    alias: 'monolog.logger'
    public: true

#  twig.extension.text: # Required by JMSTranslationBundle
#    class: Twig_Extensions_Extension_Text
#    tags: [{ name: twig.extension }]
#
#  twig.extension.intl:
#    class: Twig_Extensions_Extension_Intl
#    tags: [{ name: twig.extension }]

#    # Firewall
  surfnet_saml.saml_provider:
    class: Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\Provider\SamlProvider
#    arguments:
#      - '@request_stack'
#      - '@Surfnet\SamlBundle\Entity\HostedEntities'
#      - '@Surfnet\SamlBundle\Entity\IdentityProvider'
#      - '@logger'

  Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\Provider\SamlProvider:
    alias: surfnet_saml.saml_provider

  Surfnet\StepupSelfService\SelfServiceBundle\Service\InstitutionConfigurationOptionsService:
    alias: self_service.service.institution_configuration_options

  Surfnet\StepupSelfService\SelfServiceBundle\Service\TestSecondFactor\TestAuthenticationRequestFactory:
    alias: self_service.test_second_factor_authentication_request_factory

  Surfnet\StepupSelfService\SelfServiceBundle\Service\SelfVetMarshaller:
    alias: self_service.service.self_vet_marshaller
#  self_service.service.institution_configuration_options:
#    class: Surfnet\StepupSelfService\SelfServiceBundle\Service\InstitutionConfigurationOptionsService
#    arguments:
#      - "@surfnet_stepup_middleware_client.configuration.service.institution_configuration_options"
#    public: true

