imports:
  - { resource: 'legacy/samlstepupproviders_parameters.yml' }
  - { resource: 'legacy/global_view_parameters.yml' }
  - { resource: 'legacy/parameters.yml' }
  - { resource: 'legacy/samlstepupproviders.yml' }

services:
  twig.extension.text: # Required by JMSTranslationBundle
    class: Twig_Extensions_Extension_Text
    tags: [{ name: twig.extension }]

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags: [{ name: twig.extension }]
