imports:
  - { resource: 'openconext/samlstepupproviders_parameters.yaml' }
  - { resource: 'openconext/global_view_parameters.yaml' }
  - { resource: 'openconext/parameters.yaml' }
  - { resource: 'openconext/samlstepupproviders.yaml' }

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true


    # TODO: find the exact configuration for this
#  Surfnet\:
#    resource: '../src/'
#    exclude:
#      - '../src/Surfnet/StepupSelfService/SamlStepupProviderBundle/{DependencyInjection,Resources,Entity,Repository,Tests}'
#      - '../src/Surfnet/StepupSelfService/SamlStepupBundle/{DependencyInjection,Resources,Entity,Repository,Tests}'
#      - '../src/Kernel.php'

  logger:
    alias: 'monolog.logger'
    public: true

  surfnet_saml.saml_provider:
    class: Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\Provider\SamlProvider
    arguments:
      $identityService: '@Surfnet\StepupSelfService\SelfServiceBundle\Service\IdentityService'
      $preferredLocaleProvider: '@self_service.locale.request_stack_locale_provider'

  Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\Provider\SamlProvider:
    alias: surfnet_saml.saml_provider

  Surfnet\StepupSelfService\SelfServiceBundle\Service\InstitutionConfigurationOptionsService:
    alias: self_service.service.institution_configuration_options

  Surfnet\StepupSelfService\SelfServiceBundle\Service\TestSecondFactor\TestAuthenticationRequestFactory:
    alias: self_service.test_second_factor_authentication_request_factory

  Surfnet\StepupSelfService\SelfServiceBundle\Service\SelfVetMarshaller:
    alias: self_service.service.self_vet_marshaller
#  self_service.service.institution_configuration_options:
#    class: Surfnet\StepupSelfService\SelfServiceBundle\Service\InstitutionConfigurationOptionsService
#    arguments:
#      - "@surfnet_stepup_middleware_client.configuration.service.institution_configuration_options"
#    public: true

#  Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\Handler\AuthenticatedSessionStateHandler:
#    alias: security.authentication.custom_success_handler

  Surfnet\SamlBundle\Security\Authentication\Handler\SuccessHandler:
    class: Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\Handler\AuthenticationSuccessHandler
    arguments:
      - '@Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\AuthenticatedSessionStateHandler'
      - []
      - '@logger'
