# Use this service definition file to override services and parameters in the test environment.
# For example to mock certain services, or override a password for test.

parameters:
  middleware_credentials_password: secret

services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Surfnet\StepupSelfService\SelfServiceBundle\Service\SmsSecondFactorServiceInterface:
    class: Surfnet\StepupSelfService\SelfServiceBundle\Tests\TestDouble\Service\SmsSecondFactorService
    arguments:
        - "@surfnet_stepup_self_service_self_service.service.command"

  Surfnet\StepupSelfService\SelfServiceBundle\Service\YubikeySecondFactorServiceInterface:
    class: Surfnet\StepupSelfService\SelfServiceBundle\Tests\TestDouble\Service\YubikeySecondFactorService
    arguments:
      $commandService: "@surfnet_stepup_self_service_self_service.service.command"
      $logger: "@logger"

  Surfnet\StepupBundle\Service\SmsRecoveryTokenServiceInterface:
    class: Surfnet\StepupSelfService\SelfServiceBundle\Tests\TestDouble\Service\SmsRecoveryTokenService

  # The middleware client bundle guzzle client is overloaded to be able to pass the testcookie to the ensure MW is
  # loaded in test mode. This way people setting the testcookie in prod will not switch their mw api into testmode
  # resulting in 500 errors.
  surfnet_stepup_middleware_client.guzzle.api:
    class: GuzzleHttp\Client
    factory: ['Surfnet\StepupSelfService\SelfServiceBundle\Tests\TestDouble\Factory\GuzzleApiFactory', createApiGuzzleClient]
    arguments:
        - "%middleware_url_api%"
        - "%middleware_credentials_username%"
        - "%middleware_credentials_password%"

  surfnet_stepup_middleware_client.guzzle.commands:
    class: GuzzleHttp\Client
    factory: ['Surfnet\StepupSelfService\SelfServiceBundle\Tests\TestDouble\Factory\GuzzleApiFactory', createCommandGuzzleClient]
    arguments:
        - "%middleware_url_command_api%"
