services:
    # Firewall
    self_service.security.authentication.listener:
        class: Surfnet\StepupSelfService\SelfServiceBundle\Security\Firewall\SamlListener
        arguments:
            - "@self_service.security.authentication.handler.authenticated_user_handler"
            - "@self_service.security.authentication.saml_interaction"
            - "@logger"

    self_service.security.authentication.provider.saml:
        class: Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\Provider\SamlProvider
        arguments:
            - "@self_service.service.identity"
            - "@surfnet_saml.saml.attribute_dictionary"
            - "@self_service.locale.request_stack_locale_provider"
            - "@logger"

    self_service.security.authentication.saml_interaction:
        public: false
        class: Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\SamlInteractionProvider
        arguments:
            - "@surfnet_saml.hosted.service_provider"
            - "@surfnet_saml.remote.idp"
            - "@surfnet_saml.http.redirect_binding"
            - "@surfnet_saml.http.post_binding"
            - "@self_service.security.authentication.session.session_storage"

    # Authentication Handlers
    self_service.security.authentication.handler.authenticated_user_handler:
        public: false
        class: Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\Handler\AuthenticatedUserHandler
        arguments:
            - "@security.token_storage"
            - "@self_service.security.authentication.session.session_lifetime_guard"
            - "@self_service.security.authentication.session.session_storage"
            - "@logger"
        calls:
            - ["setNext", ["@self_service.security.authentication.handler.explicit_session_timeout"]]

    self_service.security.authentication.handler.explicit_session_timeout:
        public: false
        class: Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\Handler\ExplicitSessionTimeoutHandler
        arguments:
            - "@security.token_storage"
            - "@self_service.security.authentication.session.session_storage"
            - "@self_service.security.authentication.session.session_lifetime_guard"
            - "@security.logout.handler.session"
            - "@security.logout.handler.cookie_clearing.saml_based"
            - "@router"
            - "@logger"
        calls:
            - ["setNext", ["@self_service.security.authentication.handler.initiate_saml_request"]]

    self_service.security.authentication.handler.initiate_saml_request:
        public: false
        class: Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\Handler\InitiateSamlAuthenticationHandler
        arguments:
            - "@security.token_storage"
            - "@self_service.security.authentication.session.session_storage"
            - "@self_service.security.authentication.session.session_storage"
            - "@self_service.security.authentication.saml_interaction"
            - "@router"
            - "@surfnet_saml.logger"
            - "@logger"
        calls:
            - ["setNext", ["@self_service.security.authentication.handler.process_saml_response"]]

    self_service.security.authentication.handler.process_saml_response:
        public: false
        class: Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\Handler\ProcessSamlAuthenticationHandler
        arguments:
            - "@security.token_storage"
            - "@self_service.security.authentication.saml_interaction"
            - "@self_service.security.authentication.session.session_storage"
            - "@self_service.security.authentication.session.session_storage"
            - "@security.authentication.manager"
            - "@surfnet_saml.logger"
            - "@templating"

    self_service.security.authentication.handler.logout_success:
        class: Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\Handler\LogoutSuccessHandler
        arguments:
            - "@security.token_storage"
            - "%logout_redirect_url%"

    # Session
    self_service.security.authentication.session.session_storage:
        public: true
        class: Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\Session\SessionStorage
        arguments:
            - "@session"

    self_service.security.authentication.session.session_lifetime_guard:
        public: false
        class: Surfnet\StepupSelfService\SelfServiceBundle\Security\Authentication\Session\SessionLifetimeGuard
        arguments:
            - "@self_service.security.authentication.session.absolute_maximum_lifetime"
            - "@self_service.security.authentication.session.relative_maximum_lifetime"

    self_service.security.authentication.session.absolute_maximum_lifetime:
        public: false
        class: Surfnet\StepupSelfService\SelfServiceBundle\Value\TimeFrame
        factory: [Surfnet\StepupSelfService\SelfServiceBundle\Value\TimeFrame, ofSeconds]
        arguments:
            - "%self_service.security.authentication.session.maximum_absolute_lifetime_in_seconds%"

    self_service.security.authentication.session.relative_maximum_lifetime:
        public: false
        class: Surfnet\StepupSelfService\SelfServiceBundle\Value\TimeFrame
        factory: [Surfnet\StepupSelfService\SelfServiceBundle\Value\TimeFrame, ofSeconds]
        arguments:
            - "%self_service.security.authentication.session.maximum_relative_lifetime_in_seconds%"
