name: build-push-docker-image

on:
  workflow_dispatch:

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the latest release
        id: release
        uses: robinraju/release-downloader@v1.7
        with:
          latest: true
          fileName: "*.tar.bz2"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Set docker labels and tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/openconext/stepup-selfservice/stepup-selfservice
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=prod

      - name: Build and push the Production image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            APP_VERSION=${{ steps.release.outputs.tag_name }}
            GIT_SHA=${{ github.sha }}
          file: docker/Dockerfile.prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
